# Generated by Django 4.2.5 on 2023-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='Mis_archivos/')),
                ('date_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'archivos',
                'ordering': ['-date_at'],
            },
        ),
    ]
