# Generated by Django 4.2.5 on 2023-09-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubirArchivo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
    ]
